### This document is not work, because it's webSocket, but you can use of postman for test.

### Create message(createMessage event)
{
  "content": "Hello world!",
  "senderUsername": "john_doe",
  "roomLink": "world"
}

### Get all messages(findAllMessages event)

### Get message by id(findOneMessage even)

### Update message(updateMessage event)
{
  "content": "Updated message content"
}

### Delete message(removeMessage event)