### Create message
POST http://localhost:3000/messages
Content-Type: application/json 

{
  "content": "Hello world!",
  "senderUsername": "john_doe",
  "roomId": "651eb0b4d848fb3f4e3957db",
  "timestamp": "2023-02-18T12:34:56.789Z"
}

### Get all messages
GET http://localhost:3000/messages

### Get message by id
GET http://localhost:3000/messages/63f62c3a20c086f09c275525 

### Update message
PATCH http://localhost:3000/messages/63f62c3a20c086f09c275525
Content-Type: application/json

{
  "content": "Updated message content" 
}

### Delete message
DELETE http://localhost:3000/messages/63f62c3a20c086f09c275526